### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by sculpt0r**
According to recent changes in other repos: also the lock file was removed.

### CODE REVIEW

**Comment by sculpt0r** [comment]
Rebased on the newest development

**Review by KarolDawidziuk — CHANGES_REQUESTED** [review]
Hello, @sculpt0r 

I am not sure which node version should I test it on, and I cannot find any information about the correct version. So it looks fine on >= 12.x versions.

Since we decided to remove the lock file, also update the `.gitignore` file with the file` package-lock.json` there.

**Comment by sculpt0r** [comment]
Thank you @KarolDawidziuk for the review.

I added the lock file to the `.gitignore`. Also, I created the `.nvmrc` with node `14`. Could you take a look again?

**Review by KarolDawidziuk — CHANGES_REQUESTED** [review]
Thank you @sculpt0r for the corrections. 

LGTM! 🎉

**Review by KarolDawidziuk — APPROVED** [review]

**Pull request merged**
